EmpresaAguasAspNet/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EmpresaAguasAspNet.Models
{
    public class Client
    {
        public string ClientId { get; set; }

        [Display(Name = "Nome")]
        public string FirstName { get; set; }

        [Display(Name = "Apelido")]
        public string LastName { get; set; }

        [Display(Name = "Morada")]
        public string Adress { get; set; }

        [Display(Name = "Localidade")]
        public string Location { get; set; }

        [Display(Name = "NIF")]
        public string Tin { get; set; }


        public string Email { get; set; }

        [Display(Name = "Tipo")]
        public string UserType { get; set; }

        [Display(Name = "Nome Completo")]
        public string Name { get; set; }

        [Display(Name = "Username")]
        public string UserName { get; set; }

    }
}

EmpresaAguasAspNet/Controllers/ClientsController.cs
using EmpresaAguasAspNet.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmpresaAguasAspNet.Helper;

namespace EmpresaAguasAspNet.Controllers
{
    [Authorize(Roles = "Client")]
    public class ClientsController : Controller
    {
        private EmpresaAguasAspNetContext db = new EmpresaAguasAspNetContext();

        private ApplicationDbContext dba = new ApplicationDbContext();

        [Authorize(Roles = "Client View")]
        public ActionResult Index()
        {
            //lista de clientes
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));
            return View (CombosHelper.ListClient(userManager));
        }

        // GET: Users/Details/5
        [Authorize(Roles = "Client View")]
        public ActionResult Details(string userId)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));

            //se estiver vazio
            if (string.IsNullOrEmpty(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //se for nulo
            if (SingleHelper.GetClient(userManager, userId) == null)
            {
                return HttpNotFound();
            }

            return View(SingleHelper.GetClient(userManager, userId));

        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Client Edit")]
        public ActionResult Edit(string userId)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));
            //se estiver vazio
            if (string.IsNullOrEmpty(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (SingleHelper.GetClient(userManager, userId) == null)
            {
                return HttpNotFound();
            }
            //retorna um cliente
            return View(SingleHelper.GetClient(userManager, userId));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Client model)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));

            //se for nulo
            if (model == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ApplicationUser user = userManager.FindById(model.ClientId);
                    
                    user.Adress = model.Adress;
                    user.Location = model.Location;
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Tin = model.Tin;

                    userManager.Update(user);
                    
                    return RedirectToAction("Index","Home");
                     
                }
                catch (Exception e)
                {
                    return HttpNotFound();
                }

            }
            return View(model);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dba.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmpresaAguasAspNet/Views/Clients/Details.cshtml
@model EmpresaAguasAspNet.Models.Client

@{
    ViewBag.Title = "Detalhes do Cliente";
}

<h2>Details</h2>
<div class="text-danger"><h4>@ViewBag.Error</h4></div>

<div>
   
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { userid = Model.ClientId }) |
    @Html.ActionLink("Voltar a Lista", "Index")

</p>

EmpresaAguasAspNet/Views/Clients/Edit.cshtml
@model EmpresaAguasAspNet.Models.Client

@{
    ViewBag.Title = "Editar Cliente";
}

<h2>Editar</h2>
<h4 class="text-danger">@ViewBag.Error</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
       
        @Html.HiddenFor(model => model.ClientId, new { htmlAttributes = new { @class = "form-control" } })
              
          
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tin, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @* se for o cliente *@
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Voltar a Lista", "Index","Clients")
    }
    else
    {
        
        @Html.ActionLink("Voltar Área Pessoal", "Index", "Manage") 
    }

</div>

EmpresaAguasAspNet/Views/Clients/Index.cshtml
@model IEnumerable<EmpresaAguasAspNet.Models.Client>

@{
    ViewBag.Title = "Lista de Clientes";
}

<h2>Lista de Clientes</h2>
<h4 class="text-danger">@ViewBag.Error</h4>

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
               
                @Html.ActionLink("Editar", "Edit", new { userid = item.ClientId })|
              
                @Html.ActionLink("Detalhes", "Details", new { userid = item.ClientId })
               
               
            </td>
        </tr>
    }
</table>