EmpresaAguasAspNet/Models/Consumption.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EmpresaAguasAspNet.Models
{
    public class Consumption
    {
        [Key]
        public int ConsumptionId { get; set; }

        [Display(Name = "Data")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Inserir a {0} do consumo")]
        public DateTime ConsumptionDate { get; set; }

        [Display(Name = "Contagem")]
        [Required(ErrorMessage = "Inserir a {0}")]
        public int ConsumptionCount { get; set; }

        [Display(Name = "Cliente")]
        public string ClientId { get; set; }

        [NotMapped]
        [Display(Name = "Username")]
        public string UserClient { get; set; }

        [NotMapped]
        [Display(Name = "Contagem")]
        public string Count { get; set; }


        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

EmpresaAguasAspNet/Controllers/ConsumptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmpresaAguasAspNet.Helper;
using EmpresaAguasAspNet.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace EmpresaAguasAspNet.Controllers
{
    [Authorize(Roles = "Consumption")]
    public class ConsumptionsController : Controller
    {
        private EmpresaAguasAspNetContext db = new EmpresaAguasAspNetContext();

        private ApplicationDbContext dba = new ApplicationDbContext();


        // GET: Consumptions
        [Authorize(Roles = "Consumption View")]
        public ActionResult Index(string search)
        {
            //apanha o id do user
            string userId = User.Identity.GetUserId();
            
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));

            //encontra o utilizador
            var user = userManager.Users.ToList().Find(u => u.Id == userId);

            //lista os consumos
            var consumptions = db.Consumptions.ToList();

            List<Consumption> list = new List<Consumption>();

            //dependendo o tipo de user retorna uma lista
            if (user.UserType == UserType.Administrador.ToString())
            {
                list = CombosHelper.GetListConsumptions(consumptions).ToList();
            }
            else
            {
                list = CombosHelper.GetListConsumptionsById(consumptions, userId).ToList();
            }

            //caso a string nao esteja vazia
            if (!string.IsNullOrEmpty(search))
            {
                if (user.UserType == UserType.Administrador.ToString())
                {
                    list = CombosHelper.GetListConsumptionsContains(consumptions, search).ToList();
                }

            }

            return View(list);
        }



        // GET: Consumptions/Create
        [Authorize(Roles = "Consumption Create")]
        public ActionResult Create()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));
            //retorna os clientes mas mostra o username
            ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");
           
            return View();
        }

        // POST: Consumptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ConsumptionId,ConsumptionDate,ConsumptionCount,ClientId")] Consumption consumption)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));

            //guarda o utilizador
            string userId = User.Identity.GetUserId();

            var user = userManager.Users.ToList().Find(u => u.Id == userId);

            // Verifica o user se foi escolhido
            if (consumption.ClientId == "0")
            {
                ViewBag.ErrorClient = "Tem que selecionar um Cliente";

                ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");

                return View(consumption);
            }

            //verifica se ja existe alguma contagem
            var existsConsumption = db.Consumptions.FirstOrDefault(x =>
                x.ConsumptionDate.Month == consumption.ConsumptionDate.Month &&
                x.ConsumptionDate.Year == consumption.ConsumptionDate.Year && x.ClientId == consumption.ClientId);

            // Verifica se ja foi inserido um consumo neste mês, para este cliente
            if (existsConsumption != null)
            {
                ViewBag.Error = "Já inseriu uma contagem neste mês!";
                ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");
                return View(consumption);
            }

            //verifica se a data é anterior a que esta na lista
            var existsConsumptionDate = db.Consumptions.FirstOrDefault(x =>
                x.ConsumptionDate > consumption.ConsumptionDate && x.ClientId == consumption.ClientId);

            // Verifica se está a inserir um registo anterior ao ultimo registo
            if (existsConsumptionDate != null)
            {
                ViewBag.Error = "Não pode inserir uma contagem anterior às contagens inseridas";
                ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");
                return View(consumption);
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    db.Consumptions.Add(consumption);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                
            }

            return View(consumption);
        }

        // GET: Consumptions/Edit/5
        [Authorize(Roles = "Consumption Edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consumption consumption = db.Consumptions.Find(id);

            if (consumption == null)
            {
                return HttpNotFound();
            }

            //procura este consumo nas faturas
            var existsInInvoice = db.Invoices.FirstOrDefault(x => x.ConsumptionId == id);

            //se existir algum
            if (existsInInvoice != null)
            {
                TempData["Error"] = "Este consumo já foi Faturado. Não pode ser alterado.";
                return RedirectToAction("Index");
            }
            
            return View(consumption);
            
        }

        // POST: Consumptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ConsumptionId,ConsumptionDate,ConsumptionCount,ClientId")] Consumption consumption)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dba));

            if (consumption == null)
            {
                return HttpNotFound();
            }

            //verifica se foi feita alguma alteracao
            var exists = db.Consumptions.FirstOrDefault(x =>
                x.ConsumptionDate == consumption.ConsumptionDate &&
                x.ConsumptionCount == consumption.ConsumptionCount &&
                x.ClientId == consumption.ClientId);

            // Verifica se ja foi inserido um consumo neste mês, para este cliente
            if (exists != null)
            {
                ViewBag.Error = "Não efectuou nenhuma alteração!";
                ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");
                return View(consumption);
            }
            
            //verifica se foi alterada a data
            var existsConsumption = db.Consumptions.FirstOrDefault(x =>
                x.ConsumptionDate != consumption.ConsumptionDate &&
                x.ConsumptionCount == consumption.ConsumptionCount &&
                x.ClientId == consumption.ClientId);

            // Verifica se ja foi inserido um consumo neste mês, para este cliente
            if (existsConsumption != null)
            {
                ViewBag.Error = "Não pode alterar a data. Apenas pode alterar a contagem!";
                ViewBag.ClientId = new SelectList(CombosHelper.ListUsers(userManager), "ClientId", "UserName");
                return View(consumption);
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(consumption).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    return HttpNotFound();
                }
            }

            return View(consumption);
        }

        // GET: Consumptions/Delete/5
        [Authorize(Roles = "Consumption Delete")]
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consumption consumption = db.Consumptions.Find(id);
            if (consumption == null)
            {
                return HttpNotFound();
            }

            //procura este consumo nas faturas
            var existsInInvoice = db.Invoices.FirstOrDefault(x => x.ConsumptionId == id);

            //se existir algum faturado nao apaga
            if (existsInInvoice != null)
            {
                TempData["Error"] = "Este consumo já foi Faturado. Não pode ser eliminado.";
                return RedirectToAction("Index");
            }


            return View(consumption);
        }

        // POST: Consumptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consumption consumption = db.Consumptions.Find(id);

            if (consumption == null)
            {
                return HttpNotFound();
            }

            //procura este consumo nas faturas

EmpresaAguasAspNet/Views/Consumptions/Create.cshtml
@using Microsoft.AspNet.Identity
@model EmpresaAguasAspNet.Models.Consumption

@{
    ViewBag.Title = "Inserir Consumo";
}

<h2>Novo Consumo</h2>
<h4 class="text-danger">@ViewBag.Error</h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ConsumptionDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConsumptionDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConsumptionDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConsumptionCount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConsumptionCount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConsumptionCount, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (User.IsInRole("Admin"))
    {
        <div class="form-group">

            @Html.LabelFor(model => model.ClientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                <div class="text-danger">@ViewBag.ErrorClient</div>
            </div>

        </div>
    }
    else
    {
        <div class="form-group">

            @Html.Hidden("ClientId", User.Identity.GetUserId())

        </div>
    }


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Criar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")}
   

EmpresaAguasAspNet/Views/Consumptions/Delete.cshtml
@model EmpresaAguasAspNet.Models.Consumption

@{
    ViewBag.Title = "Apagar";
}

<h2>Apagar</h2>

<h3>Tem a certeza que quer apagar?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConsumptionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumptionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumptionCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumptionCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EmpresaAguasAspNet/Views/Consumptions/Edit.cshtml
@model EmpresaAguasAspNet.Models.Consumption

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
<h4 class="text-danger">@ViewBag.Error</h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ConsumptionId)

        <div class="form-group">
            @Html.LabelFor(model => model.ConsumptionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConsumptionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConsumptionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConsumptionCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConsumptionCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConsumptionCount, "", new { @class = "text-danger" })
            </div>
        </div>


        @Html.HiddenFor(model => model.ClientId)

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   
}

EmpresaAguasAspNet/Views/Consumptions/Index.cshtml
@model IEnumerable<EmpresaAguasAspNet.Models.Consumption>

@{
    ViewBag.Title = "Lista de Consumos";
}

<h2>Consumos</h2>

<h4 class="text-danger">@TempData["Error"]</h4>



<div class="row">
<div class="col-md-6">
    <p>
        @Html.ActionLink("Novo Consumo", "Create")
    </p>
</div>
    <div class="col-md-6">
        @if (User.IsInRole("Admin"))
        {
            using (Html.BeginForm("Index", "Consumptions", FormMethod.Get))
            {
                <p>

                    User: @Html.TextBox("search")
                    <input type="submit" value="Search" class="btn btn-default"/>
                </p>
            }
        }
    </div>
</div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ConsumptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConsumptionCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsumptionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsumptionCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserClient)
                </td>



                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.ConsumptionId }) |

                    @Html.ActionLink("Apagar", "Delete", new { id = item.ConsumptionId })
                </td>


            </tr>
        }

    </table>